services:
  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    volumes:
      - ./backend/habits.db:/app/habits.db # Persists your tasks even if the container restarts
    networks:
      - habit-network

  frontend:
    build: ./frontend
    restart: always
    networks:
      - habit-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # Opens port 80 to the public internet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - habit-network

networks:
  habit-network:
    driver: bridges