.PHONY: help setup dev-back dev-front test-back test-front lint-back lint-front clean-db reset-all

# Default target when just running 'make'
.DEFAULT_GOAL := help

help: ## Show this help message
	@echo "Usage: make [target]"
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

# --- Instalación ---
setup: ## Install all dependencies for backend and frontend
	@echo "Installing backend dependencies..."
	cd backend && . venv/bin/activate && pip install -r requirements.txt && pip install ruff
	@echo "Installing frontend dependencies..."
	cd frontend && npm install

# --- Servidores de Desarrollo ---
dev-back: ## Start the FastAPI backend server with hot-reload
	@echo "Starting FastAPI..."
	cd backend && . venv/bin/activate && uvicorn src.main:app --reload

dev-front: ## Start the Vite/React frontend development server
	@echo "Starting Vite/React..."
	cd frontend && npm run dev

# --- Pruebas y Linting ---
test-back: ## Run backend tests using pytest
	@echo "Starting test suite in Python..."
	cd backend && . venv/bin/activate && python3 -m pytest -v

test-front: ## Run frontend tests
	@echo "Starting test suite in React..."
	cd frontend && npm run test

lint-back: ## Run Ruff linter and formatter check on backend
	@echo "Running Ruff (linter/formatter)..."
	cd backend && . venv/bin/activate && ruff check . && ruff format --check .

lint-front: ## Run ESLint on frontend
	@echo "Running ESLint..."
	cd frontend && npm run lint

# --- Gestión de Usuarios ---
manage-admin: ## Create or update the admin user from environment variables
	@echo "Managing admin user..."
	cd backend && . venv/bin/activate && python3 src/manage_admin.py

# --- Gestión de Base de Datos (Migraciones) ---
migration-create: ## Create a new autogenerated migration. Usage: make migration-create msg="description"
	@echo "Creating new migration..."
	@NEXT_REV=$$(ls backend/migrations/versions/*.py 2>/dev/null | wc -l | xargs printf "%03d"); \
	cd backend && . venv/bin/activate && alembic revision --autogenerate -m "$(msg)" --rev-id "$$NEXT_REV"

migrate: ## Apply all pending migrations
	@echo "Applying migrations..."
	cd backend && . venv/bin/activate && alembic upgrade head

migrate-undo: ## Revert the last migration
	@echo "Undoing last migration..."
	cd backend && . venv/bin/activate && alembic downgrade -1

migrate-status: ## Show migration history and current status
	@echo "Migration status:"
	cd backend && . venv/bin/activate && alembic history --verbose && alembic current

# --- Utilidades de Base de Datos ---
clean-db: ## Empty the local SQLite database without deleting the file
	@echo "Cleaning SQLite database..."
	@truncate -s 0 backend/habits.db || cat /dev/null > backend/habits.db
	@chmod 666 backend/habits.db
	@echo "Database cleaned and permissions reset. It will be recreated on next start."

reset-all: clean-db setup ## Clean database and reinstall all dependencies
	@echo "Project reset to its initial state."

# --- Gestión de Backups ---
backup-manual: ## Run a manual database backup
	@echo "Running manual backup..."
	@mkdir -p backups
	DB_FILE=backend/habits.db BACKUP_DIR=backups ./backend/scripts/backup.sh
