events {}

http {
    server {
        listen 80;

        # Todo el tráfico de la API va al contenedor de FastAPI
        location /tasks/ {
            proxy_pass http://backend:8000/tasks/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /auth/ {
            proxy_pass http://backend:8000/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Todo lo demás va al contenedor del Frontend (React)
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}