import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const channel = new BroadcastChannel('reminders-channel');

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const title = payload.title || 'RECUERDA';
    const options = {
      body: payload.body,
      icon: payload.icon || '/favicon.svg',
      badge: payload.badge || '/pwa-192x192.png',
      data: payload.data || {},
      vibrate: [200, 100, 200],
    };

    // HYBRID APPROACH:
    // Check if any client (window) is currently open and focused
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
        const isAppOpen = clientList.some(client => client.focused);

        if (isAppOpen) {
          // Send message to the app to show an in-app toast instead of a system notification
          channel.postMessage({
            type: 'PUSH_RECEIVED',
            payload: { title, ...options }
          });
          // We still might want to show the notification if the user explicitly wants both,
          // but per plan, we avoid duplicates.
        } else {
          // App is closed or in background, show native notification
          return self.registration.showNotification(title, options);
        }
      })
    );
  } catch (err) {
    console.error('Push event error:', err);
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  // Open the app when notification is clicked
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return self.clients.openWindow('/');
    })
  );
});
