import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const channel = new BroadcastChannel('reminders-channel');

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const title = payload.title || 'RECUERDA';
    const options = {
      body: payload.body,
      icon: payload.icon || '/favicon.svg',
      badge: payload.badge || '/pwa-192x192.png',
      data: payload.data || {},
      vibrate: [200, 100, 200],
      tag: 'habit-reminder', // Evita duplicados apilando bajo el mismo tag
      renotify: true         // Fuerza vibración aunque el tag sea el mismo
    };

    // HYBRID APPROACH mejorado:
    event.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
        // Solo consideramos que la app está "Abierta" si al menos una ventana está VISIBLE y ENFOCADA
        const isAppVisible = clientList.some(client => client.visibilityState === 'visible' && client.focused);

        if (isAppVisible) {
          // Enviar mensaje a la app para mostrar Toast interno + Sonido
          channel.postMessage({
            type: 'PUSH_RECEIVED',
            payload: { title, ...options }
          });
          // No mostramos notificación nativa para no molestar si el usuario ya está dentro
        } else {
          // La app está en segundo plano, cerrada o bloqueada. Mostrar banner nativo.
          return self.registration.showNotification(title, options);
        }
      })
    );
  } catch (err) {
    console.error('Push event error:', err);
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Si hay una ventana abierta, enfocarla
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }
      // Si no, abrir una nueva
      if (self.clients.openWindow) {
        return self.clients.openWindow('/');
      }
    })
  );
});
