import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const channel = new BroadcastChannel('reminders-channel');

self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const payload = event.data.json();
    const title = payload.title || 'RECUERDA';
    
    // CRITICAL: Android Chrome DOES NOT support SVG icons in notifications.
    // Using PNG icons from the public directory.
    const options = {
      body: payload.body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      data: payload.data || {},
      vibrate: [300, 100, 400],
      tag: 'habit-reminder',
      renotify: true,
      requireInteraction: false
    };

    // Broadcast message to the app (if open) to show in-app feedback (Toast/Sound)
    channel.postMessage({
      type: 'PUSH_RECEIVED',
      payload: { title, ...options }
    });

    // CRITICAL: On Android Chrome, EVERY push event MUST call showNotification.
    // If we skip it (even if app is open), Chrome shows a "phantom" generic notification.
    event.waitUntil(
      self.registration.showNotification(title, options)
    );
    
  } catch (err) {
    console.error('Push event error:', err);
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }
      // Otherwise open the app
      if (self.clients.openWindow) {
        return self.clients.openWindow('/');
      }
    })
  );
});
