"""initial_base

Revision ID: 001
Revises:
Create Date: 2026-04-17 02:43:15.528316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitationcode",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_by_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "reminder",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_reminder_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminder_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "task",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("MUTED", "FRAILEJON", "TIERRA", name="priority"),
            nullable=False,
        ),
        sa.Column(
            "task_type", sa.Enum("CHECKBOX", "COUNTER", name="tasktype"), nullable=False
        ),
        sa.Column(
            "column_id",
            sa.Enum("DAILY", "MONTHLY", "ANNUALLY", "TODO", name="columnid"),
            nullable=False,
        ),
        sa.Column("target_day", sa.Integer(), nullable=True),
        sa.Column("target_month", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("is_collapsed", sa.Boolean(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("current_count", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_title"), ["title"], unique=False)
        batch_op.create_index(batch_op.f("ix_task_user_id"), ["user_id"], unique=False)

    op.create_table(
        "task_completion_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "column_id",
            sa.Enum("DAILY", "MONTHLY", "ANNUALLY", "TODO", name="columnid"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("MUTED", "FRAILEJON", "TIERRA", name="priority"),
            nullable=False,
        ),
        sa.Column("target_day", sa.Integer(), nullable=True),
        sa.Column("target_month", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("is_retroactive", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_completion_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_completion_log_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_completion_log_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("day_start_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("day_end_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("task_completion_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_completion_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_task_completion_log_task_id"))

    op.drop_table("task_completion_log")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_user_id"))
        batch_op.drop_index(batch_op.f("ix_task_title"))

    op.drop_table("task")
    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminder_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminder_task_id"))

    op.drop_table("reminder")
    op.drop_table("invitationcode")
    # ### end Alembic commands ###
