"""initial_schema

Revision ID: 001
Revises:
Create Date: 2026-04-17 02:09:23.071770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invitationcode", schema=None) as batch_op:
        batch_op.alter_column(
            "code",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        )
        batch_op.alter_column(
            "is_used",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )

    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.add_column(sa.Column("task_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "title",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            nullable=False,
            existing_server_default=sa.text("1"),
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_index(batch_op.f("idx_reminder_user_id"))
        batch_op.create_index(
            batch_op.f("ix_reminder_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_reminder_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "task_type",
            existing_type=sa.TEXT(),
            type_=sa.Enum("CHECKBOX", "COUNTER", name="tasktype"),
            nullable=False,
            existing_server_default=sa.text("'checkbox'"),
        )
        batch_op.alter_column(
            "current_count",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default=sa.text("0"),
        )
        batch_op.drop_index(batch_op.f("idx_task_user_id"))
        batch_op.create_index(batch_op.f("ix_task_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("task_completion_log", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column("task_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "task_title",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        )
        batch_op.alter_column(
            "column_id",
            existing_type=sa.TEXT(),
            type_=sa.Enum("DAILY", "MONTHLY", "ANNUALLY", "TODO", name="columnid"),
            nullable=False,
        )
        batch_op.alter_column(
            "priority",
            existing_type=sa.TEXT(),
            type_=sa.Enum("MUTED", "FRAILEJON", "TIERRA", name="priority"),
            nullable=False,
        )
        batch_op.alter_column(
            "completed_at", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.alter_column(
            "is_retroactive",
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            nullable=False,
        )
        batch_op.drop_index(batch_op.f("idx_log_user_id"))
        batch_op.drop_index(batch_op.f("idx_task_completion_log_task_id"))
        batch_op.create_index(
            batch_op.f("ix_task_completion_log_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_completion_log_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "full_name",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            existing_server_default=sa.text("'User'"),
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            existing_server_default=sa.text("'user'"),
        )
        batch_op.alter_column(
            "day_start_time",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            existing_server_default=sa.text("'08:00'"),
        )
        batch_op.alter_column(
            "day_end_time",
            existing_type=sa.TEXT(),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            existing_server_default=sa.text("'20:00'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "day_end_time",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'20:00'"),
        )
        batch_op.alter_column(
            "day_start_time",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'08:00'"),
        )
        batch_op.alter_column(
            "role",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'user'"),
        )
        batch_op.alter_column(
            "full_name",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'User'"),
        )

    with op.batch_alter_table("task_completion_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_completion_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_task_completion_log_task_id"))
        batch_op.create_index(
            batch_op.f("idx_task_completion_log_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(batch_op.f("idx_log_user_id"), ["user_id"], unique=False)
        batch_op.alter_column(
            "is_retroactive",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            nullable=True,
        )
        batch_op.alter_column(
            "completed_at", existing_type=sa.DATETIME(), nullable=True
        )
        batch_op.alter_column(
            "priority",
            existing_type=sa.Enum("MUTED", "FRAILEJON", "TIERRA", name="priority"),
            type_=sa.TEXT(),
            nullable=True,
        )
        batch_op.alter_column(
            "column_id",
            existing_type=sa.Enum(
                "DAILY", "MONTHLY", "ANNUALLY", "TODO", name="columnid"
            ),
            type_=sa.TEXT(),
            nullable=True,
        )
        batch_op.alter_column(
            "task_title",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=True,
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("task_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_user_id"))
        batch_op.create_index(batch_op.f("idx_task_user_id"), ["user_id"], unique=False)
        batch_op.alter_column(
            "current_count",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "task_type",
            existing_type=sa.Enum("CHECKBOX", "COUNTER", name="tasktype"),
            type_=sa.TEXT(),
            nullable=True,
            existing_server_default=sa.text("'checkbox'"),
        )

    with op.batch_alter_table("reminder", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminder_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminder_task_id"))
        batch_op.create_index(
            batch_op.f("idx_reminder_user_id"), ["user_id"], unique=False
        )
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("1"),
        )
        batch_op.alter_column(
            "title",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.drop_column("task_id")

    with op.batch_alter_table("invitationcode", schema=None) as batch_op:
        batch_op.alter_column(
            "is_used",
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("0"),
        )
        batch_op.alter_column(
            "code",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.TEXT(),
            nullable=True,
        )

    # ### end Alembic commands ###
