"""add timer fields to task

Revision ID: 005
Revises: 004
Create Date: 2026-05-01 23:39:14.191303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, Sequence[str], None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timer_end_time", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "timer_triggered",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("timer_triggered")
        batch_op.drop_column("timer_end_time")

    # ### end Alembic commands ###
